POSIX

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,10 +1,18 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
 export ASSUME_ALWAYS_YES=YES
 export PAGER=cat
+
+command -v zfs >/dev/null 2>&1 || { echo >&2 "zfs command is required but it's not installed.  Aborting."; exit 1; }
+command -v curl >/dev/null 2>&1 || { echo >&2 "curl command is required but it's not installed.  Aborting."; exit 1; }
+command -v sysrc >/dev/null 2>&1 || { echo >&2 "sysrc command is required but it's not installed.  Aborting."; exit 1; }
+command -v freebsd-update >/dev/null 2>&1 || { echo >&2 "freebsd-update command is required but it's not installed.  Aborting."; exit 1; }
+command -v zpool >/dev/null 2>&1 || { echo >&2 "zpool command is required but it's not installed.  Aborting."; exit 1; }
+command -v gpart >/dev/null 2>&1 || { echo >&2 "gpart command is required but it's not installed.  Aborting."; exit 1; }
+command -v gnop >/dev/null 2>&1 || { echo >&2 "gnop command is required but it's not installed.  Aborting."; exit 1; }
 
 fast_drive_list="ada0"
 root_drive_list="da0 da1"
@@ -48,31 +56,26 @@ fqdn="${hostname}.${domain}"
 host_ip=$(host "${fqdn}" | grep "has address" | awk '{print $4}')
 
 t="test"
-if [ "${TESTING:-"YES"}" = "NO" ] ; then t=""; fi
+if [ ${TESTING:-"YES"} = "NO" ] ; then t=""; fi
 
 if [ -z "${host_ip}" ]
 then
-    echo "Hostname ${fqdn} not found in DNS - setup DNS first."
-    exit 1 
+    echo >&2 "Hostname ${fqdn} not found in DNS - setup DNS first."
+    exit 1
 fi
 
 if [ -d "${temp_dir}" ] ; then rm -R "${temp_dir}"; fi
 mkdir -p "${temp_dir}"
 
 
-source ~/server/include/jail/init
-source ~/server/include/jail/create
-
-source ~/server/include/networking/init
-
-source ~/server/include/software/init
-
-source ~/server/include/system/init
-source ~/server/include/system/install
-
-source ~/server/include/user/init
-
-source ~/server/include/zfs/init
+. ~/server/include/jail/init
+. ~/server/include/jail/create
+. ~/server/include/networking/init
+. ~/server/include/software/init
+. ~/server/include/system/init
+. ~/server/include/system/install
+. ~/server/include/user/init
+. ~/server/include/zfs/init
 
 echo "Setting up ZFS."
 zfs_init
@@ -86,13 +89,9 @@ mount -t devfs devfs "${altroot}/dev"
 echo "Configuring system."
 
 system_init
-
 software_init
-
 user_init
-
 networking_init
-
 jail_init
 
 echo "Creating Jails."
@@ -100,15 +99,18 @@ echo "Creating Jails."
 echo "Set passwords."
 chroot "${altroot}" passwd "root"
 chroot "${altroot}" passwd "homeadmin"
-password=""
-while [ -z "${password// }" ]
+
+while [ -z ${password:-} ]
 do
     read -s -p "Enter ssmtp password: " password
-    if [ -z "${password// }" ] 
+    if [ -z ${password} ] 
     then 
-        echo "\nMust not be blank! try again..."
+        echo ""
+        echo "Must not be blank! try again..."
     fi
 done
+
+mkdir -p "${altroot}/usr/local/etc/ssmtp"
 echo "AuthPass=${password}" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
 
 echo "Creating install snapshots."
diff --git a/include/jail/create b/include/jail/create
--- a/include/jail/create
+++ b/include/jail/create
@@ -1,13 +1,13 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-source ~/server/scripts/setup/jail/base
-source ~/server/scripts/setup/jail/staging
-source ~/server/scripts/setup/jail/fstab_init
+. ~/server/scripts/setup/jail/base
+. ~/server/scripts/setup/jail/staging
+. ~/server/scripts/setup/jail/fstab_init
 
-function jail_create {
+jail_create () {
 
     local jail_name=${1:-}
     local jail_release=${2:-}
@@ -16,18 +16,18 @@ function jail_create {
     local jail_dir=${JAIL_DIR:-${jail_dir:-"${altroot}/usr/local/jails"}}
 
     #check variables
-    if [[ -z "${jail_name// }" ]]
+    if [ -z "${jail_name// }" ]
     then
-        echo "****Failed to create jail. Name must not be blank.****"
+        echo >&2 "****Failed to create jail. Name must not be blank.****"
         return 1
     fi
-    if [[ -z "${jail_release// }" ]]
+    if [ -z "${jail_release// }" ]
     then
-        echo "****Failed to create jail. Release must not be blank.****"
+        echo >&2 "****Failed to create jail. Release must not be blank.****"
         return 1
     fi
 
-    if [[ ! -d "${jail_dir}/mount/${jail_name}" ]]
+    if [ ! -d "${jail_dir}/mount/${jail_name}" ]
     then
         mkdir -p "${jail_dir}/mount/${jail_name}"
     fi
diff --git a/include/system/etc/fstab_init b/include/system/etc/fstab_init
--- a/include/system/etc/fstab_init
+++ b/include/system/etc/fstab_init
@@ -1,16 +1,16 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-function fstab_init {
+fstab_init () {
 
     local altroot=${1:-${ALTROOT:-${altroot:-}}}
     local backup_nfs=${BACKUP_NFS:-${backup_nfs:-}}
 
-    if [[ -z "${backup_nfs// }" ]]
+    if [ -z "${backup_nfs}" ]
     then
-        echo "****failed to create fstab. backup_nfs not set****"
+        echo >&2 "****failed to create fstab. backup_nfs not set****"
         return 1
     fi
 
diff --git a/include/system/install b/include/system/install
--- a/include/system/install
+++ b/include/system/install
@@ -1,9 +1,9 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-function system_install {
+system_install () {
 
     local root=${1:-}
     local kernel=${2:-0}
@@ -15,49 +15,49 @@ function system_install {
     local arch_valid=0
     local release_valid=0
 
-    if [[ -z "${root// }" ]]
+    if [ -z "${root}" ]
     then
-        echo "****Failed to install system. No value passed for install location.****"
+        echo >&2 "****Failed to install system. No value passed for install location.****"
         return 1
     fi
 
     for arch_check in ${valid_arch}
     do
-        if [[ ${arch} == ${arch_check} ]]
+        if [[ ${arch} = ${arch_check} ]]
         then
             local arch_valid=1
         fi
     done
     for release_check_num in ${valid_release_num}
     do
-        if [[ ${release} == ${release_check_num}-RELEASE ]]
+        if [ ${release} = ${release_check_num}-RELEASE ]
         then
             local release_valid=1
         fi
     done
-    if [[ $release_valid -ne 1 ]] || [[ $arch_valid -ne 1 ]] || [[ ! -d "${root}" ]]
+    if [ $release_valid -ne 1 -o $arch_valid -ne 1 -o ! -d "${root}" ]
     then
-        echo "****Failed to install system. Release, architecture, or root location invalid.****"
+        echo >&2 "****Failed to install system. Release, architecture, or root location invalid.****"
         return 1
     fi
 
     echo "  --Installing FreeBSD version ${release} for ${arch} to ${root}."
-    if [[ ${kernel} -eq 1 ]] ; then echo "     -with kernel"; fi
-    if [[ ${ports} -eq 1 ]] ; then echo "     -with ports"; fi
+    if [ ${kernel} -eq 1 ] ; then echo "     -with kernel"; fi
+    if [ ${ports} -eq 1 ] ; then echo "     -with ports"; fi
 
-    if [[ ! -f "${temp_dir}/base-${release}.txz" ]]
+    if [ ! -f "${temp_dir}/base-${release}.txz" ]
     then
         curl -fLo "${temp_dir}/base-${release}.txz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/${arch}/${release}/base.txz"
     fi
 
-    if [[ ${kernel} -eq 1 ]]
+    if [ ${kernel} -eq 1 ]
     then
         if [[ ! -f "${temp_dir}/kernel-${release}.txz" ]]
         then
             curl -fLo "${temp_dir}/kernel-${release}.txz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/${arch}/${release}/kernel.txz"
         fi
     fi
-    if [[ ${ports} -eq 1 ]]
+    if [ ${ports} -eq 1 ]
     then
         if [[ ! -f "${temp_dir}/ports-${release}.txz" ]]
         then
@@ -67,26 +67,26 @@ function system_install {
 
     echo "    Installing base. Please wait..."
     pv "${temp_dir}/base-${release}.txz" | tar -xf - -C "${root}"
-    if [[ ${kernel} -eq 1 ]]
+    if [ ${kernel} -eq 1 ]
     then
         echo "    Installing kernel. Please wait..."
         pv "${temp_dir}/kernel-${release}.txz" | tar -xf - -C "${root}"
     fi
-    if [[ ${ports} -eq 1 ]]
+    if [ ${ports} -eq 1 ]
     then
         echo "    Installing ports. Please wait..."
         pv "${temp_dir}/ports-${release}.txz" | tar -xf - -C "${root}"
     fi
 
-    if [[ ${REMOVE_INSTALL_FILES:-1} -eq 1 ]]
+    if [ ${REMOVE_INSTALL_FILES:-1} -eq 1 ]
     then
         echo "    Removing temp files."
         rm "${temp_dir}/base-${release}.txz"
-        if [[ ${kernel} -eq 1 ]]
+        if [ ${kernel} -eq 1 ]
         then
             rm "${temp_dir}/kernel-${release}.txz"
         fi
-        if [[ ${ports} -eq 1 ]]
+        if [ ${ports} -eq 1 ]
         then
             rm "${temp_dir}/ports-${release}.txz"
         fi
diff --git a/include/zfs/clean_disk b/include/zfs/clean_disk
--- a/include/zfs/clean_disk
+++ b/include/zfs/clean_disk
@@ -1,23 +1,21 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-function clean_disk {
+clean_disk () {
 
-    # No args? More than 1 arg?
-    if [[ $# -ne 1 ]]
+    if [ $# -ne 1 ]
     then
-        echo "****Failed to clean disk. invalid number of arquments.****"
+        echo >&2 "****Failed to clean disk. invalid number of arquments.****"
         return 1
     fi
 
     local drive=$1
 
-    # Check if arg is a drive
-    if [[ ! -e /dev/${drive} ]]
+    if [ ! -e /dev/${drive} ]
     then 
-        echo "****Failed to delete $drive - not a drive****"
+        echo >&2 "****Failed to delete $drive - not a drive****"
         return 1
     fi
 
diff --git a/include/zfs/create_pool b/include/zfs/create_pool
--- a/include/zfs/create_pool
+++ b/include/zfs/create_pool
@@ -1,9 +1,9 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-function create_pool {
+create_pool () {
 
     local pool=${1:-}
     local ztype=${2:-}
@@ -13,13 +13,13 @@ function create_pool {
 
     if [ -z "$drive_list" ]
     then
-        echo "****Failed to setup pool. drive_list is not set.****"
+        echo >&2 "****Failed to setup pool. drive_list is not set.****"
         return 1
     fi
 
     if [ -z "$altroot" ]
     then
-        echo "****Failed to setup pool. altroot is not set.****"
+        echo >&2 "****Failed to setup pool. altroot is not set.****"
         return 1
     fi
 
@@ -27,7 +27,7 @@ function create_pool {
     do
         if [ ! -e /dev/${check_drive} ]
         then
-            echo "****Failed to setup pool. $check_drive is not a valid drive.****"
+            echo >&2 "****Failed to setup pool. $check_drive is not a valid drive.****"
             return 1
         fi
     done
@@ -45,7 +45,7 @@ function create_pool {
     fi
     if [ ${type_checks_out:-0} -ne 1 ]
     then
-        echo "****Failed to setup pool. $ztype is not a valid zfs pool type.****"
+        echo >&2 "****Failed to setup pool. $ztype is not a valid zfs pool type.****"
         return 1
     fi
 
