move pid check

diff --git a/include b/include
--- a/include
+++ b/include
@@ -84,13 +84,7 @@ server_update() {
     echo "waiting for patches to complete"
     for patch in $(ls "$root/var/run/server/patches")
     do
-        echo "waiting for patch: $patch"
-        local pid=$(get_patch_pid "$1")
-        tail --pid=$pid -f "$root/var/log/server/patches/$patch.log"
-        wait $pid >/dev/null 2>&1
-        errorcheck && echoerr "failure: check log for $patch patch"
-        clear_patch_pid "$patch" "$root"
-        echo "patch complete: $patch"
+        wait_for_patch "$patch" "$root"
     done
 
     echo "running binary updates (apt)"
@@ -106,16 +100,40 @@ server_update() {
     return 0
 }
 
+wait_for_patch() {
+    echo "waiting for patch: $1"
+    local pid=$(get_patch_pid "$1")
+    tail --pid=$pid -f "$2/var/log/server/patches/$1.log"
+    while kill -0 $ppid >/dev/nul 2>&1
+    do
+        sleep 0.5s
+    done
+    errorcheck && echoerr "failure: check log for $1 patch"
+    clear_patch_pid "$1" "$2"
+    echo "patch complete: $1"
+}
+
 # 1=patch
 # 2=chroot_eval (optional)
 # 3=root (optional)
 execute_patch() {
-    echo "running ${1##*/} patch in chroot '$3'"
-    local chroot_eval=$2
-    [ "x$3" == "x" ] && local chroot_eval=
-    [ ! -d "$3/var/log/server/patches" ] && mkdir -p "$3/var/log/server/patches"
-    eval "$chroot_eval \"$SERVER_INSTALL/patches/${1##*/}\" >\"$3/var/log/server/patches/${1##*/}.log\" 2>&1 &" >/dev/null 2>&1
-    set_patch_pid "${1##*/}" "$!" "$3"
+    local ppid=$(get_patch_pid "$1")
+    if [ "x$ppid" == "x" ]
+        local chroot_eval=$2
+        if [ "x$3" == "x" ]
+        then
+            local chroot_eval=
+            echo "running ${1##*/} patch in chroot '$3'"
+        else
+            echo "running ${1##*/} patch"
+        fi
+        [ ! -d "$3/var/log/server/patches" ] && mkdir -p "$3/var/log/server/patches"
+        eval "$chroot_eval \"$SERVER_INSTALL/patches/${1##*/}\" >\"$3/var/log/server/patches/${1##*/}.log\" 2>&1 &" >/dev/null 2>&1 && \
+            set_patch_pid "${1##*/}" "$!" "$3"
+    else
+        echo "$1 patch already running - skipping"
+    fi
+    return 0
 }
 
 #checks version of patch files
@@ -153,29 +171,23 @@ get_server_setting() {
 #   2=minimum version of patch
 patch_requires() {
     ! check_version "$2" "$1" || return 0
-
     echo "required patch $1 does not meet version $2"
     local ppid=$(get_patch_pid "$1")
     if [ "x$ppid" == "x" ]
     then
-        echo "executing required patch: $1"
+        echo "required patch $1 is not currently running"
         execute_patch $1
-        local ppid=$(get_patch_pid "$1")
     fi
-    echo "required patch $1 running on pid $ppid - waiting for it to complete"
-    tail --pid=$ppid -f "/var/log/server/patches/$1.log"
-    while kill -0 $ppid >/dev/nul 2>&1
-    do
-        sleep 0.5s
-    done
+    wait_for_patch "$1"
     ! check_version "$2" "$1" && echo "required patch $1 failed" && return 1 || return 0
 }
 
 # 1=patch
 # 2=root (optional)
 get_patch_pid() {
-    [ -f "$2/var/run/server/patches/$1" ] && echo $(cat "$2/var/run/server/patches/$1") && return 0
-    echoerr "no pid for $1 patch." && return 1
+    [ -f "$2/var/run/server/patches/$1" ] && \
+        echo $(cat "$2/var/run/server/patches/$1") && \
+        return 0 || return 1
 }
 
 # 1=patch
@@ -192,22 +204,6 @@ set_patch_pid() {
 clear_patch_pid() {
     [ -f "$2/var/run/server/patches/$1" ] && rm "$2/var/run/server/patches/$1" && return 0
     echoerr "no pid for $1 patch." && return 1
-}
-
-# 1=patch
-# 2=current pid
-# 3=root (optional)
-check_pid() {
-    local ppid=$(get_patch_pid "$1" "$3")
-    local ppid=${ppid:-$2}
-
-    if [ $ppid -ne $2 ]
-    then
-        echo "$1 patch already running on pid $ppid - exiting"
-        return 0
-    fi
-
-    return 1
 }
 
 vercomp() {
