cleanup

diff --git a/include b/include
--- a/include
+++ b/include
@@ -62,13 +62,24 @@ server_update() {
 
     echo "getting latest server code from git to $root$SERVER_INSTALL"
     #get latest server code
-    [ ! -d "$root$SERVER_INSTALL" ] && git clone "$SERVER_GIT_LOCATION" "$root$SERVER_INSTALL"
-    pushd "$root$SERVER_INSTALL"
-    git remote update
+    if [ ! -d "$root$SERVER_INSTALL" ]
+    then
+        git clone "$SERVER_GIT_LOCATION" "$root$SERVER_INSTALL"
+        errorcheck && echoerr "failed to clone from git" && return 1
+    fi
+    pushd "$root$SERVER_INSTALL" >/dev/null
+    git rev-parse --git-dir > /dev/null 2>&1
+    errorcheck && popd >/dev/null && echoerr "directory not a git repo" && return 1
+    git remote update >/dev/null
+    errorcheck && popd >/dev/null && echoerr "failed to update git repo" && return 1
     local local_rev=$(git rev-parse master)
     local server_rev=$(git rev-parse origin/master)
-    [ $local_rev != $server_rev ] && git reset --hard origin/master
-    popd
+    if [ $local_rev != $server_rev ]
+    then
+        git reset --hard origin/master >dev/null
+        errorcheck && popd >/dev/null && echoerr "failed to reset git" && return 1
+    fi
+    popd >/dev/null
 
     echo "marking bin/patches executable"
     chmod +x "$root$SERVER_INSTALL/bin/"*
@@ -77,7 +88,6 @@ server_update() {
     echo "kicking off patches"
     for patch in $(ls "$root$SERVER_INSTALL/patches")
     do
-        echo "Starting patch: $patch"
         execute_patch "$patch" "$chroot_eval" "$root"
     done
 
@@ -101,18 +111,19 @@ server_update() {
 }
 
 wait_for_patch() {
-    echo "waiting for patch: $1"
-    local pid=$(get_patch_pid "$1")
-    tail --pid=$pid -f "$3/var/log/server/patches/$1.log"
+    local patch=${1##*/}
+    echo "waiting for patch: $patch"
+    local pid=$(get_patch_pid "$patch")
+    tail --pid=$pid -f "$3/var/log/server/patches/$patch.log"
     while kill -0 $ppid >/dev/nul 2>&1
     do
         sleep 0.5s
     done
-    clear_patch_pid "$1" "$3"
-    check_version "$2" "$1" && \
-        errorcheck && echoerr "patch failure: check log for $1 patch" \
+    clear_patch_pid "$patch" "$3"
+    check_version "$2" "$patch" && \
+        errorcheck && echoerr "patch failure: check log for $patch patch" \
         return 1
-    echo "patch complete: $1"
+    echo "patch complete: $patch"
     return 0
 }
 
@@ -120,22 +131,18 @@ wait_for_patch() {
 # 2=chroot_eval (optional)
 # 3=root (optional)
 execute_patch() {
-    local ppid=$(get_patch_pid "$1")
+    local patch=${1##*/}
+    local ppid=$(get_patch_pid "$patch" "$3")
     if [ "x$ppid" == "x" ]
     then
         local chroot_eval=$2
-        if [ "x$3" == "x" ]
-        then
-            local chroot_eval=
-            echo "running ${1##*/} patch"
-        else
-            echo "running ${1##*/} patch in chroot '$3'"
-        fi
+        [ "x$3" == "x" ] && local chroot_eval=
         [ ! -d "$3/var/log/server/patches" ] && mkdir -p "$3/var/log/server/patches"
-        eval "$chroot_eval \"$SERVER_INSTALL/patches/${1##*/}\" >\"$3/var/log/server/patches/${1##*/}.log\" 2>&1 &" >/dev/null 2>&1 && \
-            set_patch_pid "${1##*/}" "$!" "$3"
+        eval "$chroot_eval \"$SERVER_INSTALL/patches/$patch\" >\"$3/var/log/server/patches/$patch.log\" 2>&1 &" >/dev/null 2>&1
+        set_patch_pid "$patch" "$!" "$3"
+        echo "patch $patch runing on pid $(get_patch_pid "$patch" "$3")"
     else
-        echo "$1 patch already running - skipping"
+        echo "patch $patch already running on pid $ppid - skipping"
     fi
     return 0
 }
@@ -144,19 +151,22 @@ execute_patch() {
 #   returns 0 if the patch should run
 #   meaning either the version is unknown greater than the last run
 check_version() {
-    [ -f "/etc/server/patches/$2" ] && local local_version=$(cat "/etc/server/patches/$2")
+    local patch=${2##*/}
+    [ -f "/etc/server/patches/$patch" ] && local local_version=$(cat "/etc/server/patches/$patch")
     [ "x$local_version" == "x" ] && return 1
     vers_test "$1" "-gt" "$local_version" && return 1 || return 0
 }
 
 set_version() {
+    local patch=${2##*/}
     [ ! -d "/etc/server/patches" ] && mkdir -p "/etc/server/patches"
-    echo $1 > "/etc/server/patches/$2"
+    echo $1 > "/etc/server/patches/$patch"
     return 0
 }
 
 get_version() {
-    [ -f "$2/etc/server/patches/$1" ] && echo $(cat "$2/etc/server/patches/$1") && return 0
+    local patch=${1##*/}
+    [ -f "$2/etc/server/patches/$patch" ] && echo $(cat "$2/etc/server/patches/$patch") && return 0
     echo "0" && return 0
 }
 
@@ -164,38 +174,42 @@ get_version() {
 # 2=setting value
 # 3=alt root (optional)
 set_server_setting() {
+    local patch=${1##*/}
     [ ! -d "$3/etc/server/settings" ] && mkdir -p "$3/etc/server/settings"
-    echo "$2" > "$3/etc/server/settings/$1"
-    chmod 600 "$3/etc/server/settings/$1"
+    echo "$2" > "$3/etc/server/settings/$patch"
+    chmod 600 "$3/etc/server/settings/$patch"
     return 0
 }
 
 get_server_setting() {
-    [ -f "$2/etc/server/settings/$1" ] && echo "$(cat $2/etc/server/settings/$1)" && return 0
-    echoerr "no server setting for $1." && return 1
+    local patch=${1##*/}
+    [ -f "$2/etc/server/settings/$patch" ] && echo "$(cat $2/etc/server/settings/$patch)" && return 0
+    echoerr "no server setting for $patch" && return 1
 }
 
 #checks to make sure a required patch has been run
 #   1=patch name
 #   2=minimum version of patch
 patch_requires() {
-    ! check_version "$2" "$1" || return 0
-    echo "required patch $1 does not meet version $2"
-    local ppid=$(get_patch_pid "$1")
+    local patch=${1##*/}
+    ! check_version "$2" "$patch" || return 0
+    echo "required patch $patch does not meet version $2"
+    local ppid=$(get_patch_pid "$patch")
     if [ "x$ppid" == "x" ]
     then
-        echo "required patch $1 is not currently running"
-        execute_patch $1
+        echo "required patch $patch is not currently running"
+        execute_patch "$patch"
     fi
     wait_for_patch "$patch" $(get_version "$patch")
-    ! check_version "$2" "$1" && echo "required patch $1 failed" && return 1 || return 0
+    ! check_version "$2" "$patch" && echo "required patch $patch failed" && return 1 || return 0
 }
 
 # 1=patch
 # 2=root (optional)
 get_patch_pid() {
-    [ -f "$2/var/run/server/patches/$1" ] && \
-        echo $(cat "$2/var/run/server/patches/$1") && \
+    local patch=${1##*/}
+    [ -f "$2/var/run/server/patches/$patch" ] && \
+        echo $(cat "$2/var/run/server/patches/$patch") && \
         return 0 || return 1
 }
 
@@ -203,16 +217,18 @@ get_patch_pid() {
 # 2=value
 # 3=root (optional)
 set_patch_pid() {
+    local patch=${1##*/}
     [ ! -d "$3/var/run/server/patches" ] && mkdir -p "$3/var/run/server/patches"
-    echo "$2" > "$3/var/run/server/patches/$1"
+    echo "$2" > "$3/var/run/server/patches/$patch"
     return 0
 }
 
 # 1=patch
 # 2=root (optional)
 clear_patch_pid() {
-    [ -f "$2/var/run/server/patches/$1" ] && rm "$2/var/run/server/patches/$1" && return 0
-    echoerr "no pid for $1 patch." && return 1
+    local patch=${1##*/}
+    [ -f "$2/var/run/server/patches/$patch" ] && rm "$2/var/run/server/patches/$patch" && return 0
+    echoerr "no pid for $patch patch." && return 1
 }
 
 vercomp() {
