back to root

diff --git a/include b/include
--- a/include
+++ b/include
@@ -131,34 +131,38 @@ wait_for_patch() {
 
 set_waiting() {
     local patch=${1##*/}
-    [ ! -d "/var/run/server/waiting" ] && mkdir -p "/var/run/server/waiting"
-    touch "/var/run/server/waiting/$patch"
+    [ ! -d $root ] && local root=
+    [ ! -d "$root/var/run/server/waiting" ] && mkdir -p "$root/var/run/server/waiting"
+    touch "$root/var/run/server/waiting/$patch"
     return 0
 }
 
 check_waiting() {
     local patch=${1##*/}
-    [ -f "/var/run/server/waiting/$patch" ] && return 0 || return 1
+    [ ! -d $root ] && local root=
+    [ -f "$root/var/run/server/waiting/$patch" ] && return 0 || return 1
 }
 
 clear_waiting() {
     local patch=${1##*/}
-    [ -f "/var/run/server/waiting/$patch" ] && rm "/var/run/server/waiting/$patch"
+    [ ! -d $root ] && local root=
+    [ -f "$root/var/run/server/waiting/$patch" ] && rm "$root/var/run/server/waiting/$patch"
     return 0
 }
 
 get_log_name() {
     local patch=${1##*/}
-    [ ! -d "/var/log/server/patches" ] && mkdir -p "/var/log/server/patches"
-    [ ! -f "/var/log/server/patches/$patch.log" ] && \
-        echo "/var/log/server/patches/$patch.log" && return 0
+    [ ! -d $root ] && local root=
+    [ ! -d "$root/var/log/server/patches" ] && mkdir -p "$root/var/log/server/patches"
+    [ ! -f "$root/var/log/server/patches/$patch.log" ] && \
+        echo "$root/var/log/server/patches/$patch.log" && return 0
     local ln=1
-    while [ -f "/var/log/server/patches/$patch.$ln.log" ]
+    while [ -f "$root/var/log/server/patches/$patch.$ln.log" ]
     do
         ln=$((ln+1))
     done
-    mv "/var/log/server/patches/$patch.log" "/var/log/server/patches/$patch.$ln.log"
-    echo "/var/log/server/patches/$patch.log"
+    mv "$root/var/log/server/patches/$patch.log" "$root/var/log/server/patches/$patch.$ln.log"
+    echo "$root/var/log/server/patches/$patch.log"
     return 0
 }
 
@@ -175,13 +179,15 @@ execute_patch() {
 
 patch_failure() {
     local patch=${1##*/}
-    [ ! -d "/etc/server/patches" ] && mkdir -p "/etc/server/patches"
-    echo "$2" > "/etc/server/patches/$patch.failure"
+    [ ! -d $root ] && local root=
+    [ ! -d "$root/etc/server/patches" ] && mkdir -p "$root/etc/server/patches"
+    echo "$2" > "$root/etc/server/patches/$patch.failure"
 }
 
 get_status() {
-    [ ! -f "/etc/server/patches/$patch.failure" ] && return 0
-    return $(cat "/etc/server/patches/$patch.failure")
+    [ ! -d $root ] && local root=
+    [ ! -f "$root/etc/server/patches/$patch.failure" ] && return 0
+    return $(cat "$root/etc/server/patches/$patch.failure")
 }
 
 async_patch() {
@@ -205,7 +211,7 @@ patch_requires() {
     else
         get_status "$patch"
         errorcheck && echoerr "required patch $patch failed" && return 1
-        check_version "$version" "$patch" || return 0
+        check_version "$version" "$patch" && echo "required patch $patch already on latest version." && return 0
         echo "required patch $patch does not meet version $version - executing"
         execute_patch "$patch"
     fi
@@ -215,44 +221,50 @@ patch_requires() {
 
 get_patch_pid() {
     local patch=${1##*/}
-    [ -f "/var/run/server/patches/$patch" ] && \
-        echo $(cat "/var/run/server/patches/$patch") && \
+    [ ! -d $root ] && local root=
+    [ -f "$root/var/run/server/patches/$patch" ] && \
+        echo $(cat "$root/var/run/server/patches/$patch") && \
         return 0 || return 1
 }
 
 set_patch_pid() {
     local patch=${1##*/}
-    [ ! -d "/var/run/server/patches" ] && mkdir -p "/var/run/server/patches"
+    [ ! -d $root ] && local root=
+    [ ! -d "$root/var/run/server/patches" ] && mkdir -p "$root/var/run/server/patches"
     echo "$2" > "/var/run/server/patches/$patch"
     return 0
 }
 
 clear_patch_pid() {
     local patch=${1##*/}
-    [ -f "/var/run/server/patches/$patch" ] && rm "/var/run/server/patches/$patch" && return 0
+    [ ! -d $root ] && local root=
+    [ -f "$root/var/run/server/patches/$patch" ] && rm "$root/var/run/server/patches/$patch" && return 0
     echoerr "no pid for $patch patch." && return 1
 }
 
 #checks version of patch files
-#   returns 0 if the patch should run
+#   returns 1 if the patch should run
 #   meaning either the version is unknown or less than or equal to the last run
 check_version() {
     local patch=${2##*/}
-    [ -f "/etc/server/patches/$patch" ] && \
-        local local_version=$(cat "/etc/server/patches/$patch")
+    [ ! -d $root ] && local root=
+    [ -f "$root/etc/server/patches/$patch" ] && \
+        local local_version=$(cat "$root/etc/server/patches/$patch")
     [ "x$local_version" == "x" ] && return 1
     vers_test "$1" "-gt" "$local_version" && return 1 || return 0
 }
 
 set_version() {
     local patch=${2##*/}
-    [ ! -d "/etc/server/patches" ] && mkdir -p "/etc/server/patches"
-    echo $1 > "/etc/server/patches/$patch"
+    [ ! -d $root ] && local root=
+    [ ! -d "$root/etc/server/patches" ] && mkdir -p "$root/etc/server/patches"
+    echo "$1" > "/etc/server/patches/$patch"
     return 0
 }
 
 set_server_setting() {
     local setting=$1
+    [ ! -d $root ] && local root=
     [ ! -d "$root/etc/server/settings" ] && mkdir -p "$root/etc/server/settings"
     echo "$2" > "$root/etc/server/settings/$setting"
     chmod 600 "$root/etc/server/settings/$setting"
@@ -261,6 +273,7 @@ set_server_setting() {
 
 get_server_setting() {
     local setting=$1
+    [ ! -d $root ] && local root=
     [ -f "/etc/server/settings/$setting" ] && echo "$(cat /etc/server/settings/$setting)" && return 0
     echoerr "no server setting named $setting" && return 1
 }
