remove jq and fix display name

diff --git a/bin/service-scripts/services-status b/bin/service-scripts/services-status
--- a/bin/service-scripts/services-status
+++ b/bin/service-scripts/services-status
@@ -10,18 +10,18 @@ do
     for service in $(docker-compose --project-directory /opt/server/docker/$stack --env-file /opt/server/environment ps -q)
     do
 
-        docker inspect $service >/dev/null 2>&1
+        service_name=$(docker inspect $service --format '{{ index .Config.Labels "com.docker.compose.service"}}') >/dev/null 2>&1
         if [ $? = 1 ]; then
-            echo -e "  $service: \e[33m▲ Not Started\e[0m"
+            echo -e "  $service_name: \e[33m▲ Not Started\e[0m"
             end="FAIL"
         else
-            state=$(docker inspect $service | jq ".[] .State.Health.Status" | sed 's/"//g')
-            if [ $state = "null" ]; then
-                echo -e "  $service: \e[33m▲ Unknown\e[0m"
+            state=$(docker inspect $service --format '{{ .State.Health.Status }}')
+            if [ $? = 1 ]; then
+                echo -e "  $service_name: \e[33m▲ Unknown\e[0m"
                 end="FAIL"
             else
                 if [ -z $state ] || [ "$state" != "healthy" ]; then
-                    echo -e "  $service: \e[31m▲ Failed\e[0m"
+                    echo -e "  $service_name: \e[31m▲ Failed\e[0m"
                     end="FAIL"
                 fi
             fi
