bug fixes

diff --git a/bin/service-scripts/services-status b/bin/service-scripts/services-status
--- a/bin/service-scripts/services-status
+++ b/bin/service-scripts/services-status
@@ -7,10 +7,21 @@ end="No services failed!"
 for service in $(/opt/server/bin/service-scripts/list-all-services)
 do
 
-    state=$(docker inspect $service | jq ".[] .State.Health.Status" | sed 's/"//g')
-    if [ -z $state ] || [ "$state" != "healthy" ]; then
-        echo -e "  $service: \e[31m▲ Failed\e[0m"
+    docker inspect $service >/dev/null 2>&1
+    if [ $? = 1 ]; then
+        echo -e "  $service: \e[33m▲ Not Started\e[0m"
         end="FAIL"
+    else
+        state=$(docker inspect $service | jq ".[] .State.Health.Status" | sed 's/"//g')
+        if [ $state = "null" ]; then
+            echo -e "  $service: \e[33m▲ Unknown\e[0m"
+            end="FAIL"
+        else
+            if [ -z $state ] || [ "$state" != "healthy" ]; then
+                echo -e "  $service: \e[31m▲ Failed\e[0m"
+                end="FAIL"
+            fi
+        fi
     fi
 
 done
